# Site settings
title: Dongxu LI personal page
email: dongxuli1005@gmail.com
description: "Dongxu LI personal page"
baseurl: ""
url: "dxli94.github.io"
#blogurl: "http://yihui-he.github.io/blog"
#twitter_username: karpathy
github_username:  dxli94

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
